#!/bin/sh

# Clone frontend
git clone git@github.com:scriptype/graphql-presentation-react-apollo.git react-apollo

# Clone graphql api
git clone git@github.com:scriptype/graphql-presentation-node-graphql.git node-graphql
