# Prod specific setup.
version: '3.3'
services:
  web:
    env_file: ./react-apollo/.env.production
    networks:
      - app_network
    environment:
      NODE_ENV: production

  nginx:
    restart: always
    build: ./nginx
    networks:
      - app_network
    ports:
      - 5000:80

  graphql:
    networks:
      - app_network
    environment:
      NODE_ENV: production

networks:
  app_network:
